/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AcknowledgeEvent, IonButtonType, IonIconSlot, IonIconVariant } from "./components/hakion-button/hakion-button";
import { Color, Expand, Fill, Mode } from "./interface";
export namespace Components {
    interface HakionButton {
        /**
          * The color to use from your application's color palette. Default options are: "primary", "secondary", "tertiary", "success", "warning", "danger", "light", "medium", and "dark".
         */
        "color": Color;
        /**
          * If true, the user cannot interact with the button.
         */
        "disabled": boolean;
        /**
          * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
         */
        "download": string | undefined;
        /**
          * This attribute lets you specify how wide the button should be. By default, buttons are inline blocks, but setting this attribute will change the button to a full-width block element.
         */
        "expand": Expand;
        "fill": Fill;
        /**
          * If this property is set, an anchor tag will be rendered.
         */
        "href": string;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconName": string;
        /**
          * Use custom icon by specifying a path. If set, any value set on `ionIcon` will be ignored.
         */
        "iconSize": 'small' | 'large' | undefined;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconSlot": IonIconSlot;
        /**
          * Use custom icon by specifying a path. If set, any value set on `ionIcon` will be ignored.
         */
        "iconSrc": string;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconVariant": IonIconVariant;
        /**
          * The mode determines which platform styles to use.
         */
        "mode": Mode;
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of link types.
         */
        "rel": string | undefined;
        /**
          * The button shape.
         */
        "shape": string | undefined;
        /**
          * If true, activates a button with a heavier font weight.
         */
        "strong": boolean;
        "text": string;
        /**
          * The color to use for the text if the attribute `text` is set. Will not affect anything between <slot>
         */
        "textColor": Color;
        /**
          * The type of the button.
         */
        "type": IonButtonType;
    }
    interface HakionDarkModeToggle {
        "mode": string;
    }
    interface HakionRippleEffect {
    }
    interface HakionUiRoot {
    }
    interface MyAlert {
        /**
          * The first name
         */
        "text": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ThreeElementExample {
    }
}
declare global {
    interface HTMLHakionButtonElement extends Components.HakionButton, HTMLStencilElement {
    }
    var HTMLHakionButtonElement: {
        prototype: HTMLHakionButtonElement;
        new (): HTMLHakionButtonElement;
    };
    interface HTMLHakionDarkModeToggleElement extends Components.HakionDarkModeToggle, HTMLStencilElement {
    }
    var HTMLHakionDarkModeToggleElement: {
        prototype: HTMLHakionDarkModeToggleElement;
        new (): HTMLHakionDarkModeToggleElement;
    };
    interface HTMLHakionRippleEffectElement extends Components.HakionRippleEffect, HTMLStencilElement {
    }
    var HTMLHakionRippleEffectElement: {
        prototype: HTMLHakionRippleEffectElement;
        new (): HTMLHakionRippleEffectElement;
    };
    interface HTMLHakionUiRootElement extends Components.HakionUiRoot, HTMLStencilElement {
    }
    var HTMLHakionUiRootElement: {
        prototype: HTMLHakionUiRootElement;
        new (): HTMLHakionUiRootElement;
    };
    interface HTMLMyAlertElement extends Components.MyAlert, HTMLStencilElement {
    }
    var HTMLMyAlertElement: {
        prototype: HTMLMyAlertElement;
        new (): HTMLMyAlertElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLThreeElementExampleElement extends Components.ThreeElementExample, HTMLStencilElement {
    }
    var HTMLThreeElementExampleElement: {
        prototype: HTMLThreeElementExampleElement;
        new (): HTMLThreeElementExampleElement;
    };
    interface HTMLElementTagNameMap {
        "hakion-button": HTMLHakionButtonElement;
        "hakion-dark-mode-toggle": HTMLHakionDarkModeToggleElement;
        "hakion-ripple-effect": HTMLHakionRippleEffectElement;
        "hakion-ui-root": HTMLHakionUiRootElement;
        "my-alert": HTMLMyAlertElement;
        "my-component": HTMLMyComponentElement;
        "three-element-example": HTMLThreeElementExampleElement;
    }
}
declare namespace LocalJSX {
    interface HakionButton {
        /**
          * The color to use from your application's color palette. Default options are: "primary", "secondary", "tertiary", "success", "warning", "danger", "light", "medium", and "dark".
         */
        "color"?: Color;
        /**
          * If true, the user cannot interact with the button.
         */
        "disabled"?: boolean;
        /**
          * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
         */
        "download"?: string | undefined;
        /**
          * This attribute lets you specify how wide the button should be. By default, buttons are inline blocks, but setting this attribute will change the button to a full-width block element.
         */
        "expand"?: Expand;
        "fill"?: Fill;
        /**
          * If this property is set, an anchor tag will be rendered.
         */
        "href"?: string;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconName"?: string;
        /**
          * Use custom icon by specifying a path. If set, any value set on `ionIcon` will be ignored.
         */
        "iconSize"?: 'small' | 'large' | undefined;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconSlot"?: IonIconSlot;
        /**
          * Use custom icon by specifying a path. If set, any value set on `ionIcon` will be ignored.
         */
        "iconSrc"?: string;
        /**
          * If this property is set, an anchor tag will be rendered. If set to "icon-only," all other content will be ignored.
         */
        "iconVariant"?: IonIconVariant;
        /**
          * The mode determines which platform styles to use.
         */
        "mode"?: Mode;
        "onAcknowledge"?: (event: CustomEvent<AcknowledgeEvent>) => void;
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of link types.
         */
        "rel"?: string | undefined;
        /**
          * The button shape.
         */
        "shape"?: string | undefined;
        /**
          * If true, activates a button with a heavier font weight.
         */
        "strong"?: boolean;
        "text"?: string;
        /**
          * The color to use for the text if the attribute `text` is set. Will not affect anything between <slot>
         */
        "textColor"?: Color;
        /**
          * The type of the button.
         */
        "type"?: IonButtonType;
    }
    interface HakionDarkModeToggle {
        "mode"?: string;
    }
    interface HakionRippleEffect {
    }
    interface HakionUiRoot {
    }
    interface MyAlert {
        /**
          * The first name
         */
        "text"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ThreeElementExample {
    }
    interface IntrinsicElements {
        "hakion-button": HakionButton;
        "hakion-dark-mode-toggle": HakionDarkModeToggle;
        "hakion-ripple-effect": HakionRippleEffect;
        "hakion-ui-root": HakionUiRoot;
        "my-alert": MyAlert;
        "my-component": MyComponent;
        "three-element-example": ThreeElementExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hakion-button": LocalJSX.HakionButton & JSXBase.HTMLAttributes<HTMLHakionButtonElement>;
            "hakion-dark-mode-toggle": LocalJSX.HakionDarkModeToggle & JSXBase.HTMLAttributes<HTMLHakionDarkModeToggleElement>;
            "hakion-ripple-effect": LocalJSX.HakionRippleEffect & JSXBase.HTMLAttributes<HTMLHakionRippleEffectElement>;
            "hakion-ui-root": LocalJSX.HakionUiRoot & JSXBase.HTMLAttributes<HTMLHakionUiRootElement>;
            "my-alert": LocalJSX.MyAlert & JSXBase.HTMLAttributes<HTMLMyAlertElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "three-element-example": LocalJSX.ThreeElementExample & JSXBase.HTMLAttributes<HTMLThreeElementExampleElement>;
        }
    }
}
