# This is a basic workflow to help you get started with Actions

name: Outline CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the next branch
  push:
    branches:
      - next
      - dev
      - alpha
      - beta
      - rc
      - /^issue/
      - /^task/
      - /^feature/
      - /^bug/
  pull_request:
    branches:
      - next
      - dev
      - alpha
      - beta
      - rc
      - /^issue/
      - /^task/
      - /^feature/
      - /^bug/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    name: Installation & Caching
    runs-on: ubuntu-latest
    container:
      image: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --prefer-offline

  test:
    name: Testing & Linting
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install from cache
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn lint

  build-dist:
    name: Build Package(s)
    runs-on: ubuntu-latest
    needs: test
    container:
      image: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install from cache
        run: yarn install --prefer-offline

      - name: Build
        run: yarn build
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: test
    container:
      image: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        id: storybook-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: storybook-static/
          key: ${{ runner.os }}-storybook-${{ hashFiles('./storybook-static/') }}
          restore-keys: |
            ${{ runner.os }}-storybook-

      - name: Install from cache
        run: yarn install --prefer-offline

      - name: Build Storybook
        run: yarn storybook.prod

  upload-storybook-artifact:
    name: Upload Storybook Artifact
    runs-on: ubuntu-latest
    needs: build-storybook
    container:
      image: node:14
    if: github.ref == 'refs/heads/feature/storybook-deploy-action'
    steps:
      - uses: actions/cache@v2
        id: storybook-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: storybook-static/
          key: ${{ runner.os }}-storybook-${{ hashFiles('./storybook-static/') }}
          restore-keys: |
            ${{ runner.os }}-storybook-

      # @see https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v2
        with:
          name: storybook-latest
          path: storybook-static/
          retention-days: 1
