# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the next branch
  push:
    branches: [ next, dev, alpha, beta, rc, /^issue/, /^task/, /^feature/, /^bug/ ]
  pull_request:
    branches: [ next, dev, alpha, beta, rc, /^issue/, /^task/, /^feature/, /^bug/ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container: 
      image: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install
        run: yarn install --cache-folder .yarn

      # Runs a single command using the runners shell
      - name: Lint
        run: yarn lint

      # Runs a single command using the runners shell
      - name: Build
        run: yarn build
        
      # Runs a single command using the runners shell
      - name: Build Storybook
        run: yarn storybook.prod
