on: push
name: Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
      - name: Slack Notification
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          GITHUB_ACTOR: ${GITHUB_ACTOR}
          GITHUB_ACTION: ${GITHUB_ACTION}
          GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          GITHUB_REF: ${GITHUB_REF}
          GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}
          SLACK_CHANNEL: 'github-ci'
          SLACK_COLOR: '#efefef'
          SLACK_ICON: 'https://github.com/<Github User>.png?size=48'
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: 'A new commit has been pushed to ${{ steps.vars.outputs.short_ref }}'
          SLACK_TITLE: 'Slack Notification'
          SLACK_USERNAME: 'schlack-bot'