name: Storybook Deployment
on:
  workflow_run:
    workflows: ['Build & Test Codebase']
    branches:
      - next
    types:
      - completed

jobs:
  # Basic setup job to prepare codebase.
  setup:
    name: Installation & Caching
    runs-on: ubuntu-latest

    # The steps for the setup job.
    steps:
      # @see https://github.com/marketplace/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # @see https://github.com/marketplace/actions/cache
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --prefer-offline

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: setup

    # The steps for the build-storybook job.
    steps:
      # @see https://github.com/marketplace/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # @see https://github.com/marketplace/actions/cache
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # @see https://github.com/marketplace/actions/cache
      - uses: actions/cache@v2
        id: storybook-cache
        with:
          path: storybook-static/
          key: ${{ runner.os }}-storybook-${{ hashFiles('./storybook-static/') }}
          restore-keys: |
            ${{ runner.os }}-storybook-

      - name: Install from cache
        run: yarn install --prefer-offline

      - name: Build Storybook
        run: yarn storybook.prod

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-storybook

    steps:
      # @see https://github.com/marketplace/actions/cache
      - uses: actions/cache@v2
        id: storybook-cache
        with:
          path: storybook-static/
          key: ${{ runner.os }}-storybook-${{ hashFiles('./storybook-static/') }}
          restore-keys: |
            ${{ runner.os }}-storybook-
      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     # Required, workflow file name or ID
      #     workflow: build.yml
      #     workflow_conclusion: success
      #     branch: next
      #     name: storybook-latest
      #     # Optional, directory where to extract artifact.
      #     path: storybook/
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: storybook-static
          commit_message: 'chore(deploy): Storybook'
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
