name: Storybook Deployment
on:
  workflow_run:
    workflows: ["Build & Test Codebase"]
    branches: 
      - next
      - feature/storybook-deploy-action
    types: 
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: node:14

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: storybook-latest
          path: storybook

      - name: Display structure of downloaded files
        run: ls -lah ./storybook
